# Generated by Django 4.1.2 on 2022-10-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveBigIntegerField(),
        ),
    ]
